apiVersion: v1
kind: Service
metadata:
  name: codemancers-node-app-service
spec:
  selector:
    app: codemancers-node-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codemancers-node-app
  labels:
    app: codemancers-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codemancers-node-app
  template:
    metadata:
      labels:
        app: codemancers-node-app
    spec:
      containers:
      - name: codemancers-node-app
        image: nihalkaradan/codemancers-crud-app:1.4
        env:
          # Use secret in real usage
        - name: HOST
          value: mysql
        - name: PASSWORD
          value: password
        ports:
        - containerPort: 3000
