apiVersion: v1
kind: ConfigMap
metadata:
  name: usermanagement-dbcreation-script
data: 
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS mydb;
    CREATE DATABASE mydb; 
    USE mydb;
    CREATE TABLE shop (id int NOT NULL AUTO_INCREMENT,name VARCHAR(255), active BOOLEAN,PRIMARY KEY (id)) ;
